const StatusCodeMessages = {
  200: "Thành công",
  201: "Tạo mới thành công",
  4000: "Yêu cầu không hợp lệ",
  4001: "Lỗi xác thực dữ liệu",
  4002: "Thiếu mã lớp",
  4003: "Cần xác thực",
  4004: "Không khớp dữ liệu",
  4005: "OTP không hợp lệ hoặc đã hết hạn",
  4006: "Cần xác thực OTP trước khi đặt lại mật khẩu hoặc phiên đã hết hạn",
  4007: "Bạn không có quyền truy cập tài nguyên này",
  4008: "Người dùng không có vai trò phù hợp",
  4009: "Người dùng không phải là học sinh",
  4040: "Không tìm thấy lớp với mã đã cung cấp",
  4041: "Không tìm thấy lớp với ID yêu cầu",
  4042: "Không tìm thấy người dùng",
  4043: "Học sinh chưa tham gia lớp này",
  4044: "Không tìm thấy dữ liệu yêu cầu",
  4045: "Không tìm thấy lượt tham gia yêu cầu",
  4046: "Không tìm thấy bài tập yêu cầu",
  4047: "Không tìm thấy đáp án yêu cầu",
  4048: "Không tìm thấy câu hỏi bài tập yêu cầu",
  4049: "Không tìm thấy đăng ký yêu cầu",
  4090: "Học sinh đã tham gia lớp này",
  4091: "Người dùng đã được kích hoạt",
  4092: "Tên đăng nhập đã được sử dụng",
  4093: "Mã học sinh đã tồn tại",
  4094: "Đã tồn tại bài nộp cho lượt tham gia này",
  4100: "Đăng nhập thất bại",
  4101: "Refresh token không hợp lệ hoặc đã hết hạn",
  4102: "Người dùng chưa được xác thực",
  4200: "Lượt tham gia chưa bắt đầu",
  4201: "Lượt tham gia đã nộp bài",
  4202: "Đã hết thời gian nộp bài",
  4203: "Không có đáp án đúng cho câu hỏi",
  4204: "Không có đăng ký chờ duyệt cho lớp này",
  5000: "Lỗi máy chủ nội bộ",
  5001: "Gửi email thất bại",
};

export default StatusCodeMessages;
